=== MaciejSocha/pkom/burgerownia.dtd
<!ELEMENT burgerownia (burger*)>
<!ELEMENT burger (nazwa, składnik*, alergen*)>
<!ELEMENT nazwa (#PCDATA)>
<!ELEMENT składniki (składnik+)
<!ELEMENT składnik (#PCDATA)>
<!ELEMENT alergeny (alergen*)
<!ELEMENT alergen (#PCDATA)>

=== MaciejSocha/pkom/burgerownia.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="burgerownia.css" type="text/css" ?>
<!DOCTYPE burgerownia SYSTEM "burgerownia.dtd">
<!-- Enum: vege vegetarian mięsny|  -->
<burgerownia>
	<burger mięsność="mięsny">
		<nazwa>CheeseBurger</nazwa>
		<składniki>
			<składnik>ser</składnik>
			<składnik>mięso</składnik>
			<składnik>bułka</składnik>
		</składniki>
		<alergeny>
			<alergen>laktoza</alergen>
		</alergeny>
		<cena>12</cena>
	</burger>
	<burger  mięsność="mięsny">
		<nazwa>HamBurger</nazwa>
		<składniki>
			<składnik>mięso</składnik>
			<składnik>bułka</składnik>
		</składniki>
		<cena>10</cena>
	</burger>
	<burger mięsność="wegański">
		<nazwa>TekturaBurger</nazwa>
		<składniki>
			<składnik>bułka</składnik>
		</składniki>
		<cena>30</cena>
	</burger>
</burgerownia>
